"""empty message

Revision ID: 32c8c2d8b292
Revises: 763139103fcd
Create Date: 2020-04-17 14:41:11.000188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c8c2d8b292'
down_revision = '763139103fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lendbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('bookname', sa.String(length=100), nullable=True),
    sa.Column('classroom', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sendtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lendbook_sendtime'), 'lendbook', ['sendtime'], unique=False)
    op.create_table('seekbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('bookname', sa.String(length=100), nullable=True),
    sa.Column('classroom', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sendtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seekbook_sendtime'), 'seekbook', ['sendtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seekbook_sendtime'), table_name='seekbook')
    op.drop_table('seekbook')
    op.drop_index(op.f('ix_lendbook_sendtime'), table_name='lendbook')
    op.drop_table('lendbook')
    op.drop_table('book')
    # ### end Alembic commands ###
