"""empty message

Revision ID: 4d099aafd0bd
Revises: 32c8c2d8b292
Create Date: 2020-04-17 14:54:51.227864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d099aafd0bd'
down_revision = '32c8c2d8b292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seekbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('bookname', sa.String(length=100), nullable=True),
    sa.Column('classroom', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sendtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seekbook_sendtime'), 'seekbook', ['sendtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seekbook_sendtime'), table_name='seekbook')
    op.drop_table('seekbook')
    # ### end Alembic commands ###
